// <auto-generated/>
using System.Reflection;

[assembly: AssemblyCompanyAttribute("AIT GmbH & Co. KG")]
[assembly: AssemblyProductAttribute("AIT.VisualStudio.TestTools")]
[assembly: AssemblyCopyrightAttribute("Copyright © 2015, AIT GmbH & Co. KG")]
[assembly: AssemblyVersionAttribute("0.4.0")]
[assembly: AssemblyFileVersionAttribute("0.4.0")]
[assembly: AssemblyInformationalVersionAttribute("0.4.0-beta002")]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.4.0";
    }
}
